name: LWA
favicon: null
layout_spectrum: 1
typography_spectrum: 0
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e44436'
    - '#ffffff'
    - '#b9b9af'
    - '#e39189'
    - '#6a2c15'
  brandStrength: 0.9817182067781687
  lightness: 0.7329775639809668
  saturation: 0.856307607376948
  rhythmicContrast: 0.24132096208631992
purpose: []
