name: LWA
favicon: null
layout_spectrum: 0.73574
typography_spectrum: 0
title: Leadership With Awareness
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ec9422'
    - '#ededed'
    - '#000000'
    - '#ff0000'
    - '#ffff00'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
