name: LWA
favicon: null
layout_spectrum: 0.46281474037095904
typography_spectrum: 0.15344388969242573
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.9817182067781687
  lightness: 0.7329775639809668
  saturation: 0.856307607376948
  rhythmicContrast: 0.24132096208631992
purpose: []
